### ISSUE TITLE
Set up linting settings for the repository

### ISSUE THREAD

**Issue by skarred14** [ethereum-oasis-op/baseline#16]
## Overview

As a developer, I would like to make sure that the codebase is linted using best practices for maintaining and managing well styled code. Currently, the `api/`, `radish34/`, `messenger/`, have varying linting settings making it difficult to have a consistent linter. In addition, the solidity contracts in `contracts/` are not fully linted, and might need to re-consider replacing `solhint` with `ethlint`

### Reference

- [Linting and compilation scripts](https://github.com/codfish/cod-scripts)
- [ESLint Config](https://github.com/codfish/eslint-config-codfish)
- [Ethlint](https://github.com/duaraghav8/Ethlint)
- [Solhint](https://github.com/protofire/solhint)

### Acceptance

- Script to lint, fix, and validate code after linting .js and .sol files
- Pre-commit hooks are updated to check linting prior to commits

## Tasks

- [ ] Update linter spec for radish34/
- [ ] Run build and deployment scripts

**Disclaimer: This is a broad stroke and a sample feature request. It would need to be further updated (potentially broken down into further feature requests), based on discussions with other members of the Oasis community

**Comment by balajipachai** [comment]
In recent times I have created a template for blockchain + node.js projects, which consists of eslint configs, solhint configured, solidity code coverage, etc, [Link to the repo](https://github.com/balajipachai/custom-oracle-implementation/tree/project-template-blockchain-nodejs-combined) 
If @skarred14  @breakpointer  @bitwiseguy can have a look at it and suggest if we can adopt some settings from there or not?, that would be really helpful

**Comment by skarred14** [comment]
Also refer to: https://github.com/codfish/cod-scripts
https://github.com/kentcdodds/kcd-scripts
