### ISSUE TITLE
npm i broken in bri-3 project

### ISSUE THREAD

**Issue by ognjenkurtic** [ethereum-oasis-op/baseline#799]
## Expected Behavior

npm i on a fresh repo should work

## Actual Behavior

npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @nomicfoundation/hardhat-chai-matchers@1.0.6
npm ERR! Found: ethers@6.12.1
npm ERR! node_modules/ethers
npm ERR!   dev ethers@"^6.12.0" from the root project
npm ERR!   peer ethers@"^6.1.0" from @nomicfoundation/hardhat-ethers@3.0.5
npm ERR!   node_modules/@nomicfoundation/hardhat-ethers
npm ERR!     dev @nomicfoundation/hardhat-ethers@"^3.0.5" from the root project
npm ERR!   2 more (ethr-did, ethr-did-resolver)

## Steps to Reproduce the Problem

  1. Pull the repo
  1. get to bri-3 folder
  1. run npm i

Note: Currentl workaround is to run npm i --force

**Comment by biscuitdey** [comment]
Completed.
